name: erllm
channels:
  - defaults
  - pytorch
  - huggingface
dependencies:
  - python=3.11
  - pandas=2.1.1
  - numpy
  - scikit-learn=1.3
  - tqdm=4.65
  - transformers=4.32
  - cpuonly
  - pytorch=2.1
  - scipy
  - nltk
  - pillow
  - sentencepiece
  - pip:
      - openai==0.28.1
      - py_stringmatching==0.4.3
